### ISSUE TITLE
大三，开始也是结束

### ISSUE THREAD

**Issue by louchaooo** [louchaooo/louchaooo.github.io#9]

**Comment by ohlinge** [comment]
超表哥可以的，文采技术都不错！学习了~

**Comment by louchaooo** [comment]
@ohlinge 哈哈，这语文都不及格的人还文采，，表哥别笑我了，技术还得努力啊

**Comment by ohlinge** [comment]
真的是，表哥别谦虚了。都大三了，一起努力~

**Comment by louchaooo** [comment]
@ohlinge  共勉！！！

**Comment by nncode** [comment]
# 认真读完，收藏了。很不错 💪

**Comment by louchaooo** [comment]
@nncode 我难神不愧我难神

**Comment by myearring** [comment]
作为妹纸。也想像你一样疯狂一把，可是现在无奈在公司上班。。。

**Comment by louchaooo** [comment]
@myearring 随便写的渣渣文还有妹纸来看，受宠若惊，，，在公司环境不应该更好吗，有兴趣一起玩啊
